- name: Symlinking {{ src_file }} runlevel 0
  file: src=/etc/init.d/{{ src_file }} dest=/etc/rc0.d/K01{{ src_file }} state=link

- name: Symlinking {{ src_file }} runlevel 1
  file: src=/etc/init.d/{{ src_file }} dest=/etc/rc1.d/K01{{ src_file }} state=link

- name: Symlinking {{ src_file }} runlevel 2
  file: src=/etc/init.d/{{ src_file }} dest=/etc/rc2.d/S99{{ src_file }} state=link

- name: Symlinking {{ src_file }} runlevel 3
  file: src=/etc/init.d/{{ src_file }} dest=/etc/rc3.d/S99{{ src_file }} state=link

- name: Symlinking {{ src_file }} runlevel 4
  file: src=/etc/init.d/{{ src_file }} dest=/etc/rc4.d/S99{{ src_file }} state=link

- name: Symlinking {{ src_file }} runlevel 5
  file: src=/etc/init.d/{{ src_file }} dest=/etc/rc5.d/S99{{ src_file }} state=link

- name: Symlinking {{ src_file }} runlevel 6
  file: src=/etc/init.d/{{ src_file }} dest=/etc/rc6.d/K01{{ src_file }} state=link
