---
# file: roles/cloudman_image/tasks/main.yml
#   Build the base machine image
#
#   See /cloudman_image/defaults/cloudman.yml for enabling/disabling
#   individual task groups

- include: packages.yml
  when: cm_install_packages

- include: libraries.yml
  when: cm_install_libraries

- include: system_users.yml
  when: cm_add_system_users

- include: install_venvburrito.yml username='galaxy' user_home='/home/galaxy'
  when: cm_venvburrito

- include: install_venvburrito.yml username='{{ default_user }}' user_home='{{ default_user_home }}'  #'
  when: cm_venvburrito

- include: system_environment.yml
  when: cm_system_environment

- include: s3fs.yml
  when: cm_install_s3fs

- include: nginx.yml
  when: cm_configure_nginx

- include: proftpd.yml
  when: cm_install_proftpd

- include: novnc.yml
  when: cm_install_novnc

- include: cleanup.yml
  when: cm_cleanup
