---
# Install s3fs

- name: Download s3fs
  get_url: url=https://github.com/s3fs-fuse/s3fs-fuse/archive/v{{ s3fs_version }}.tar.gz dest=/tmp/s3fs.tar.gz

- name: Create temporary directory
  command: mktemp -d
  register: tempdir

- name: Unarchive s3fs
  unarchive: src=/tmp/s3fs.tar.gz dest={{ tempdir.stdout }} copy=no

- name: Install s3fs
  command: "{{ item }} chdir='{{ tempdir.stdout }}/s3fs-fuse-{{ s3fs_version }}'"
  with_items:
    - ./autogen.sh
    - ./configure --prefix=/usr
    - make
    - make install

- name: Remove temporary directory
  file: path={{ tempdir.stdout }} state=absent
