---
# Setup system environment

- name: Setup system-wide vimrc
  copy: src=vimrc dest=/etc/vim/vimrc

- name: Setup /etc/bash.bashrc
  lineinfile: dest=/etc/bash.bashrc line="{{ item }}"
  with_items:
    - "alias 'lt=ls -ltr'"
    - "alias 'll=ls -l'"
    - "export PATH={{ galaxyFS_base_dir }}/tools/bin:{{ postgresql_bin_dir }}:$PATH"  #"

- name: Create a symlink placeholder to the Galaxy app dir
  shell: ln -s {{ galaxy_server_dir }} ~/galaxy
  sudo_user: "{{ item }}"
  ignore_errors: yes
  with_items:
    - "{{ default_user }}"
    - "{{ galaxy_user_name }}"

- name: Disable all default MOTD
  shell: chmod -x /etc/update-motd.d/*

- name: Disable specific MOTD notices
  shell: path={{ item }} mode=0644 state=touch
  with_items:
    - /etc/update-motd.d/90-updates-available
    - /etc/update-motd.d/98-fsck-at-reboot

- name: Add custom login splash MOTD
  copy: src=motd/00-header dest=/etc/update-motd.d/00-header mode=0755

- name: Enable reboot notice MOTD
  file: path=/etc/update-motd.d/98-reboot-required mode=0755 state=touch

- name: Enable motd
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PrintMotd\ no' line='PrintMotd yes'

- name: Disable last login ssh message
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PrintLastLog\ yes' line='PrintLastLog no'

- name: Create Ipython config dir
  shell: mkdir -p ~/.ipython/profile_default
  sudo_user: "{{ item }}"
  with_items:
    - "{{ default_user }}"
    - "{{ galaxy_user_name }}"

- name: Setup Ipython env
  copy: src=ipython_config.py dest=~/.ipython/profile_default/ipython_config.py mode=0644
  sudo_user: "{{ item }}"
  with_items:
    - "{{ default_user }}"
    - "{{ galaxy_user_name }}"

- name: Place supervisord.conf file
  copy: src=supervisor/supervisord.conf dest=/etc/supervisord.conf

- name: Create supervisor program conf dir
  file: path=/etc/supervisor/conf.d state=directory

- name: Place supervisor program conf files
  copy: src=supervisor/{{ item }} dest=/etc/supervisor/conf.d/{{ item }}
  with_items:
    - nginx.conf
    # - slurm.conf

# - name: Place postgres supervisor program conf file
#   template: src=postgres_supervisor.j2 dest=/etc/supervisor/conf.d/postgres.conf

# - name: Place galaxy supervisor program conf file
#   template: src=galaxy_supervisor.j2 dest=/etc/supervisor/conf.d/galaxy.conf

- name: Place supervisor init.d file
  copy: src=supervisor/supervisord_init dest=/etc/init.d/supervisord mode=0755

- name: Remove nginx init script
  file: path=/etc/init.d/nginx state=absent

- name: Place Galaxy init file
  template: src=galaxy_init.j2 dest=/etc/init.d/galaxy mode=0755
