---
# Configure nginx

- name: Configure PAM for nginx auth
  copy: src=nginx.pam dest=/etc/pam.d/nginx

- name: Create nginx conf CLU template files
  file: path=/etc/nginx/{{ item }} state=touch
  with_items:
    - commandline_utilities_http.conf
    - commandline_utilities_https.conf

- name: Create nginx conf file
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf

- name: Place nginx error files
  unarchive: src=nginx_errdoc.tar.gz dest=/usr/share/nginx/html

- name: Create nginx upload_store dir
  file: state=directory path={{ nginx_upload_store_path }}

- name: Reload nginx config
  service: name=nginx state=reloaded
