---
# Variables used during the image build-process

# System user details
default_user: ubuntu
default_user_home: /home/ubuntu

# CloudMan details
cm_hg_repo: https://bitbucket.org/galaxy/cloudman/raw/tip

# Details about additional software being installed
s3fs_version: 1.77
proftpd_package_url: https://s3.amazonaws.com/cloudman/galaxy-proftpd-1.3.5_gxycm-20140910b01-trusty_amd64.deb
nginx_package_url: https://s3.amazonaws.com/cloudman/galaxy-nginx-1.4.7_gxycm-20140902b01-trusty_amd64.deb

# novnc setup details
novnc_install_dir: /opt/galaxy/novnc
vnc_user: ubuntu
vnc_display: 1
vnc_depth: 16
vnc_geometry: 1024x768
